### ISSUE TITLE
Can't find file

### ISSUE THREAD

**Issue by AniOjha** [farazBhatti/Human-Body-Measurements-using-Computer-Vision#1]
extract_measurements.py tries to open a file 'data/customBodyPoints.txt' which is not found. Is this file supposed to be generated and how?

**Comment by farazBhatti** [comment]
Hi , find this file here
[customBodyPoints.txt](https://github.com/farazBhatti/Human-Body-Measurements-using-Computer-Vision/files/5886235/customBodyPoints.txt)

**Comment by AniOjha** [comment]
Thank you, it worked.

**Comment by farazBhatti** [comment]
also if code helped, you can star this repo so that more people can find it. thanks
________________________________
