### ISSUE TITLE
libraries requirements to run the code

### ISSUE THREAD

**Issue by gyanprakash0221** [farazBhatti/Human-Body-Measurements-using-Computer-Vision#10]
What all libraries should someone have to run this code ?

**Comment by farazBhatti** [comment]
Are you having any issues?

**Comment by gyanprakash0221** [comment]
I wanted to run the code and check its working for a project. So can you help me with it moving forward in order to get myself going what all libraries and dependencies I must install in my local machine to get it running.

**Comment by farazBhatti** [comment]
most of the dependencies are in the requiurements.txt file. if you have python3 then do 
`pip3 install -r requirements.txt` . It should install all requirements
