### ISSUE TITLE
About arg --height 

### ISSUE THREAD

**Issue by MapleHock** [farazBhatti/Human-Body-Measurements-using-Computer-Vision#12]
In your example of using inference.py, there is a argument -ht for inputing human height. I think it's used as a reference length to convert 3D representation into realistic one.  But I checked the reference/call stack of arg.height, it's called as 'height' in inference.py funcion 'main' defined in demo.py, and again called as 'height' in extract_measurements.extract_measurements, and again called as 'height' in extract_measurements.calc_measurement.
BUT in this function, there is no more usage of 'height'.  Besides the output results with different input heights but same image have same 'height' output value.
So I guess your code didn't use arg height. How can I fix it?

**Comment by farazBhatti** [comment]
height is being used as input inorder to extract body measurements

**Comment by MapleHock** [comment]
> height is being used as input inorder to extract body measurements

yes, I think so. And I understand it should be a reference length to map 3d virtual model size to a realistic one.  But I cannot see this argument to be a standard length unit for the measurement and affect the output.

Here is how I checked your demo input and how this issue came. I just input the same example photo but changed the input height like the screenshot below.
![issue](https://user-images.githubusercontent.com/42485228/126854773-5a3bd139-a772-464e-8dc2-fd4a13cd3074.png)
I think when the input height change from 180 to 80, all the output length like measurement(arm length, shoulder width and so on) should be multiplied by 80/180, or some other shrink factors. BUT, the inference.py gave me just two identical results.

So, I track the calling of the argument --height. I find after the call of "arg height" is end at function extract_measurements.calc_measurement without any call more.  So I think you omit to use the "input height" to correct the measurement of the virtual 3d model

**Comment by websocketing** [comment]
@MapleHock  你好，你现在还在研究身体部位测量吗？？？

**Comment by farazBhatti** [comment]
ive updated the code, i mistakenly commented a line

**Comment by websocketing** [comment]
@farazBhatti I want to measure all parts of the human body. Can you tell me a good solution? I hope I can get your email so that it is more convenient for me to contact you.

**Comment by farazBhatti** [comment]
@websocketing , faraz7123@live.com.
