### ISSUE TITLE
opendr not installing

### ISSUE THREAD

**Issue by MdFaysal97** [farazBhatti/Human-Body-Measurements-using-Computer-Vision#13]
ERROR: No matching distribution found for opendr

**Comment by vl4dimir** [comment]
I had a problem with this as well, but the very first error thrown from opendr installation was for `numpy` not being found. `pip install numpy` fixed it.

**Comment by MdFaysal97** [comment]
Yes it was resolved by individual installing.
Did you test this app? If yes , then how many tests did you conduct ? and
what's the accuracy?
Thanks and regards

**Comment by vl4dimir** [comment]
I had no luck installing it at all, got stuck many times with Python dependency errors, gave up. 😐

**Comment by AmazingGrace-D** [comment]
I was able to install it after a few errors and tests

pip3 install chumpy
sudo apt-get install libosmesa6-dev

Solved the problem

**Comment by BhaumikThakkar** [comment]
sudo apt install libosmesa6-dev

sudo apt-get install build-essential

sudo apt-get install libgl1-mesa-dev

sudo apt-get install libglu1-mesa-dev

sudo apt-get install freeglut3-dev

sudo pip install opendr

source: https://github.com/akanazawa/hmr/issues/82#issuecomment-557430371
