### ISSUE TITLE
How to build my own customBodyPoints.txt file

### ISSUE THREAD

**Issue by AlyanQ** [farazBhatti/Human-Body-Measurements-using-Computer-Vision#16]
Hi, I'm currently doing a very similar project where I need to extract the measurements from a 3D model. Could you please tell me the exact method you used to get the control points on the 3D object? Much appreciated.

**Comment by AlyanQ** [comment]
Hi @jpcurbelo , I've followed your steps till number 4, aka "Then I organized them to be consecutive". I am not too familiar with .obj file format, how would I go about making sure these points were consecutive? They seem to have small patterns, should I keep them in an ascending/descending order? Thanks for your help so far.

**Comment by jpcurbelo** [comment]
Hi, @AlyanQ . Actually, I now realized that that step would only make sense depending on the .obj files you are using. Anyway, once one has extracted the point coordinates, they may appear unsorted - in terms of forming a "circumference", for example. You can just pick one of them and then, find the nearer point, add the distance, and so on. You may see this in the figure of my control points for the neck girth - sorry for the low resolution. I think this is more likely to happen in girth measurements than in length measurements. I hope that helps!
![neck_unsorted](https://user-images.githubusercontent.com/78277407/139600870-fafad845-0bf9-409d-bb70-cc149aae87a9.png)
![neck_sorted](https://user-images.githubusercontent.com/78277407/139600873-b0845254-f8cd-4b44-8c5e-1b2275278c46.png)

**Comment by zamanhassan5** [comment]
@AlyanQ  brother aree you done with extracting measurements

**Comment by chengbilian** [comment]
Hello, are the control points you selected the vertices of the triangle mesh? Or are they irrelevant to the triangle vertices? Looking forward to your reply.

**Comment by jpcurbelo** [comment]
> Hello, are the control points you selected the vertices of the triangle mesh? Or are they irrelevant to the triangle vertices? Looking forward to your reply.

Yes, the points are selected from the mesh. It would be something like in the images:
![image](https://github.com/user-attachments/assets/852a5947-424a-44b8-bb39-440cb39478be)
![image](https://github.com/user-attachments/assets/e12e9432-5484-4182-a115-f231bcf56ee1)

**Comment by chengbilian** [comment]
Thank you for your reply
