### ISSUE TITLE
Waist measurement 

### ISSUE THREAD

**Issue by AmazingGrace-D** [farazBhatti/Human-Body-Measurements-using-Computer-Vision#17]
Hi, I am working on a project to get the waist measurement from a picture/video. I just came across this repo and I would like to know how I can convert the image or video to 3D. I believe a 3D format is what is required for this body measurement you have here to work?

**Comment by farazBhatti** [comment]
@AmazingGrace-D , thnks for your intrest. It make 3D image automatically. If you want to dig a bit more then you could see[this repo](https://github.com/akanazawa/hmr) as I've used it in my project.
