### ISSUE TITLE
Code use and paper writing.

### ISSUE THREAD

**Issue by jjunyong-e** [farazBhatti/Human-Body-Measurements-using-Computer-Vision#18]
I'm writing a paper that predicts body changes after a specific experiment after measuring the body using the code, but is it possible to use the code?

I can't find a way to contact you, so I'm asking this.

**Comment by farazBhatti** [comment]
@jjunyong-e , thank you for showing interest. yes, you may use this code by giving proper citations, please.
Thanks....

**Comment by jjunyong-e** [comment]
thank you, I'll leave a message when I submit paper
