### ISSUE TITLE
3D model output based based on gender

### ISSUE THREAD

**Issue by Amjad234** [farazBhatti/Human-Body-Measurements-using-Computer-Vision#22]
Currently, when running `inference.py` we get a generated `obj` file, which contain the 3d model, and the measurements are extracted from it.
The model is always the same shape, regardless if the input image's gender.

Is there a way to know the gender and generate a different 3d model based on that?

Thanks

**Comment by farazBhatti** [comment]
currently model is trained only for male human body type.
