### ISSUE TITLE
ENQUIRY 

### ISSUE THREAD

**Issue by Choice104** [farazBhatti/Human-Body-Measurements-using-Computer-Vision#23]
Thanks for putting so much effort into this...
What is the effectiveness of this your work? Or rather what is the percentage correlation of this work? Is there are presentation like a video to see how it was tested?

**Comment by farazBhatti** [comment]
Hi, thanks for reaching out. In terms of effectiveness, I have not found out precision and recall but it would be good exercise. I think readme has all the necessary things to run this repo if you still face problems please go ahead to ask here...

**Comment by Choice104** [comment]
I am not a programmer... I am exploring the possibilities involved in
this... I have been on this research for a while... Is there a way I can
get to your outside here?

**Comment by farazBhatti** [comment]
Here is my LinkedIn account. you may message me for further queries...

**Comment by Choice104** [comment]
I have requested for connection with the name Eseoghene Choice... Thanks

**Comment by farazBhatti** [comment]
No connection request from your side showing

**Comment by Choice104** [comment]
Please reach me on @Eseoghene Choice ***@***.***> or
Eseoghene Choice at LinkedIn
