### ISSUE TITLE
Sequence of running the code files

### ISSUE THREAD

**Issue by batool04** [farazBhatti/Human-Body-Measurements-using-Computer-Vision#24]
I am facing an issue while running the code. Firstly i do not know the exact steps to be performed like step by step loading files and running them.  Secondly, i do not know where to write commands and then create an inference. Can you please give a step by step guide which can help me to run this code. There are a lot .py files and i do not know which should i run first.

**Comment by farazBhatti** [comment]
HI @batool04 , thanks for your interest in the project. What exactly are you referring to. all the commands have been mentioned in the readme file.
e.g
for running inference:
python3 inference.py -i <path to Image1> -ht <height in cm>
replace <path to image1> with path to your image.

**Comment by batool04** [comment]
thanks for your response sir. It means i have to run above mentioned command on command prompt? and secondly all the files which are given like utils.py, extract measurements.py etc I have to run them all? if yes then what would be sequence to run them. Actually there are many .py files and the thing which is source of confusion for me is that which file should i run first.  I have installed all required libraries and i am using python 3.7.

**Comment by farazBhatti** [comment]
No, you only have to run
python3 inference.py -i <path to Image> -ht <height in cm>

for getting results.
