### ISSUE TITLE
installing opendr

### ISSUE THREAD

**Issue by negjafari** [farazBhatti/Human-Body-Measurements-using-Computer-Vision#27]
Hi, 
I'm running project in python 3.6 as you said in issues and I'm really stuck installing opendr.
I saw in issues you suggesting opendr version 0.78 but seems it works only in python version 2 
here is my installed libraries by running pip freeze command:
absl-py==1.4.0
apptools==5.2.0
astor==0.8.1
backcall==0.2.0
cached-property==1.5.2
chumpy==0.70
colorama==0.4.5
configobj==5.0.8
cvxpy==1.1.19
cycler==0.11.0
Cython==0.29.7
dataclasses==0.8
decorator==4.4.2
ecos==2.0.7.post1
envisage==6.1.1
et-xmlfile==1.1.0
fancyimpute==0.3.2
gast==0.5.3
grpcio==1.48.2
h5py==3.1.0
imageio==2.15.0
importlib-metadata==4.8.3
importlib-resources==5.4.0
ipdb==0.13.13
ipython==7.16.3
ipython-genutils==0.2.0
jdcal==1.4.1
jedi==0.17.2
joblib==1.1.1
keras==2.10.0
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.2
kiwisolver==1.3.1
knnimpute==0.1.0
Markdown==3.3.7
matplotlib==3.3.4
mayavi==4.7.1
mock==5.0.1
networkx==2.5.1
np-utils==0.6.0
numpy==1.16.1
opencv-python==4.6.0.66
openpyxl==2.6.2
osqp==0.6.2.post8
parso==0.7.1
pickleshare==0.7.5
Pillow==8.4.0
prompt-toolkit==3.0.3
protobuf==3.19.6
pyface==7.4.4
Pygments==2.14.0
PyOpenGL==3.1.0
pyparsing==2.4.7
PyQt5==5.10.1
python-dateutil==2.8.2
PyWavelets==1.1.1
qdldl==0.1.5.post3
scikit-image==0.17.2
scikit-learn==0.21.3
scipy==1.2.1
scs==3.2.2
sip==4.19.8
six==1.16.0
tensorboard==1.13.1
tensorflow==1.13.1
tensorflow-estimator==1.13.0
termcolor==1.1.0
threadpoolctl==3.1.0
tifffile==2020.9.3
tomli==1.2.3
traitlets==4.3.3
traits==5.1.1
traitsui==7.4.3
typing_extensions==4.1.1
vtk==8.1.2
wcwidth==0.2.6
Werkzeug==2.0.3
zipp==3.6.0

also I want to know which version of pillow you are using because the latest version pillow==8.4.0 doesn't work with python 3.6

thank you in advance

**Comment by farazBhatti** [comment]
try version 6.2.2

**Comment by negjafari** [comment]
For pillow or opener?

**Comment by farazBhatti** [comment]
Pillow version 6.2.2

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by negjafari** [comment]
Thank you 
I appreciate it if you can give me a hint about installing opendr
Which version did you use?

**Comment by hamzakhalil798** [comment]
@negjafari  You will have to manually install opendr from   https://github.com/polmorenoc/opendr    
Pip install opendr didnt work for me (on windows)
