### ISSUE TITLE
3D construction

### ISSUE THREAD

**Issue by batool04** [farazBhatti/Human-Body-Measurements-using-Computer-Vision#29]
I run the model but i am unable to understand where 3D construction is being performed. Deeplab v3 is used for segmentation and HMR for 3D. Firstly why both models are being used. And secondly, i do not know where is 3D mesh being generated. I would be glad if you clear my confusion.

**Comment by farazBhatti** [comment]
1- Semantic segmentation model is to make sure that image of human is used to make 3D model other wise model is not accurate.
2 - 3D model is made in HMR part of code.
3 - you would have to do some changes in HMR code to get 3D mesh as output.

**Comment by batool04** [comment]
alright thanks for your help.
