### ISSUE TITLE
Running project

### ISSUE THREAD

**Issue by cameronking4** [farazBhatti/Human-Body-Measurements-using-Computer-Vision#3]
How do I run this project?

**Comment by cameronking4** [comment]
I get this stuck in ipdb after running:  python3 inference.py -i sample_data/input/ramzan1.jpeg -ht 170

**Comment by cameronking4** [comment]
See issue here: <img width="576" alt="Screen Shot 2021-02-18 at 1 46 37 PM" src="https://user-images.githubusercontent.com/35708477/108425732-ba33a000-71ef-11eb-9bce-897801fed375.png">

**Comment by cameronking4** [comment]
@farazBhatti

**Comment by cameronking4** [comment]
Stuck installing opendr dependency. 
pip install opendr does not not work (nor sudo pip install or pip3 install)
Running on python 3.9 and mac OS

**Comment by farazBhatti** [comment]
@cameronking4  what version of tensorflow are you using? this code has been tested on 1.13.1

**Comment by farazBhatti** [comment]
try using  `pip3 install opendr==0.78`  to install opendr

**Comment by cameronking4** [comment]
I'll try that. I'm running newest version of tensorflow2

**Comment by cameronking4** [comment]
<img width="1438" alt="Screen Shot 2021-02-18 at 10 16 57 PM" src="https://user-images.githubusercontent.com/35708477/108465518-06560300-7237-11eb-96cb-27cf4af26aae.png">
pip3 install opendr==0.78 didn't work for me :(

**Comment by cameronking4** [comment]
Can I get your email? I'd be willing to pay for a web demo

**Comment by cameronking4** [comment]
<img width="1241" alt="Screen Shot 2021-02-18 at 10 26 33 PM" src="https://user-images.githubusercontent.com/35708477/108466391-68633800-7238-11eb-859e-212661404674.png">

**Comment by farazBhatti** [comment]
code is tested on Python version 3.6.6. . I am sure we can figure this out without any exchange of money :). You can keep posting questions here so that someone else looking can also be benefited.

but still, you can directly msg me: l 'faraz7123@live.com'.

**Comment by cameronking4** [comment]
Thanks I sent you email. I'm still stuck trying to install opendr
