### ISSUE TITLE
Tensorflow conflict Error in Notebook

### ISSUE THREAD

**Issue by mahajandeepakshi03** [farazBhatti/Human-Body-Measurements-using-Computer-Vision#33]
> DuplicateFlagError: The flag 'log_dir' is defined twice. First from absl.logging, Second from src.config.  Description from first occurrence: directory to write logfiles into

Having this error while importing the modules.

**Comment by farazBhatti** [comment]
what version are you using? Repo uses tensorflow==1.13.1.

**Comment by farazBhatti** [comment]
@mahajandeepakshi03 notebook has been updated(thanks to [Hamza Khalil](https://github.com/hamzakhalil798)). Please give it a try.
