### ISSUE TITLE
Wanted to know how you got the custombody points.

### ISSUE THREAD

**Issue by shubhamkvpl** [farazBhatti/Human-Body-Measurements-using-Computer-Vision#34]
Hello Faraz, 
This is not an issue. But I would like to know how did construct the custombody points text file.

**Comment by farazBhatti** [comment]
@shubhamkvpl , it was manually built. for further details you can go through [this](https://github.com/zengyh1900/3D-Human-Body-Shape) repo.Thanks

**Comment by shubhamkvpl** [comment]
Thanks for your quick response. 
Manually build means you have projected all the vertices and manually select the group of points for calculating the measurements?

**Comment by farazBhatti** [comment]
Exactly. We need this file as the model only outputs 3D model the problem is from where should measure("waist" for example). This file has coordinates or group of points which tells the algorithm where to take the measurement from  resulting 3D model.

**Comment by shubhamkvpl** [comment]
Thank you @farazBhatti
