### ISSUE TITLE
Model File not generating

### ISSUE THREAD

**Issue by MalikZohaibMustafa** [farazBhatti/Human-Body-Measurements-using-Computer-Vision#35]
The Model File.pkl is not being generated.

Moreover why do we have to give height attributre? the model should predict it based on input image na.

Modify it such that we only have to give the image path.

**Comment by MuhammadAshiqAmeer** [comment]
i think height should be given. You cant predict measurements from an image without  a reference. The model is determining the measurements referring  the height .

**Comment by MalikZohaibMustafa** [comment]
Alright
