### ISSUE TITLE
model download is not working

### ISSUE THREAD

**Issue by Osiyomeoh** [farazBhatti/Human-Body-Measurements-using-Computer-Vision#39]
HTTPSConnectionPool(host='people.eecs.berkeley.edu', port=443): Max retries exceeded with url: /~kanazawa/cachedir/hmr/models.tar.gz (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f1aa2f68fd0>, 'Connection to people.eecs.berkeley.edu timed out. (connect timeout=1200000)'))

**Comment by farazBhatti** [comment]
https://people.eecs.berkeley.edu/~kanazawa/cachedir/hmr/models.tar.gz
Can you try to download manually using above line?

**Comment by Osiyomeoh** [comment]
it's now working thanks
