### ISSUE TITLE
Don't have output

### ISSUE THREAD

**Issue by kentlohr** [farazBhatti/Human-Body-Measurements-using-Computer-Vision#4]
when i run"python3 inference.py -i IMG123.jpg -ht 170"
there was no output
when i run "python inference.py -i IMG123.jpg -ht 170"
absl.flags._exceptions.DuplicateFlagError: The flag 'log_dir' is defined twice. First from src.config, Second from absl.logging.  Description from first occurrence: Where to save training models

**Comment by farazBhatti** [comment]
try using python virtual env for inference. Install all the packages needed in that environment and then run it
