### ISSUE TITLE
training for thin, medium

### ISSUE THREAD

**Issue by osamaaldnoh** [farazBhatti/Human-Body-Measurements-using-Computer-Vision#40]
training for thin, medium

_Originally posted by @farazBhatti in https://github.com/farazBhatti/Human-Body-Measurements-using-Computer-Vision/issues/38#issuecomment-1914153481_
            
Brother, please, can you guide me to training for thin, medium and wide bodies?

**Comment by farazBhatti** [comment]
For more broader body types, one would have to train [HMR](https://github.com/akanazawa/hmr) model.

**Comment by osamaaldnoh** [comment]
> For more broader body types, one would have to train [HMR](https://github.com/akanazawa/hmr) model.

Brother, thanks for the response
If I want to extract body measurements for anyone who is skinny, average, or very fat, I train the HMR model
Duplicate of #
