### ISSUE TITLE
Value Error

### ISSUE THREAD

**Issue by mohsinmshabbir** [farazBhatti/Human-Body-Measurements-using-Computer-Vision#43]
> ValueError: Variable resnet_v2_50/conv1/weights already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined at:
> 
>   File "C:\Users\HP\anaconda3\envs\tensorflow_env3\lib\site-packages\tensorflow\python\framework\ops.py", line 1801, in __init__
>     self._traceback = tf_stack.extract_stack()
>   File "C:\Users\HP\anaconda3\envs\tensorflow_env3\lib\site-packages\tensorflow\python\framework\ops.py", line 3300, in create_op
>     op_def=op_def)
>   File "C:\Users\HP\anaconda3\envs\tensorflow_env3\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
>     return func(*args, **kwargs)

I'm running a Python Notebook provided and somehow when I execute the last cell it is giving me this error

**Comment by farazBhatti** [comment]
what version of TensorFlow are you using?

**Comment by mohsinmshabbir** [comment]
> what version of TensorFlow are you using?

TensorFlow version: 1.13.1

**Comment by mohsinmshabbir** [comment]
> what version of TensorFlow are you using?

TensorFlow version: 1.13.1
Was closed accidentally

**Comment by farazBhatti** [comment]
@mohsinmshabbir I've updated the notebook. Give it a try.
