### ISSUE TITLE
TensorFlow  compiler flags.

### ISSUE THREAD

**Issue by Rut-B** [farazBhatti/Human-Body-Measurements-using-Computer-Vision#47]
hi @farazBhatti 
I tried to run your code in google collab and got this error:

2024-05-15 06:53:52.668420: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2024-05-15 06:53:52.758075: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2024-05-15 06:53:52.759211: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

do you have idea how to solve it?

**Comment by farazBhatti** [comment]
code was written for cpu execution and not gpu.

**Comment by Rut-B** [comment]
hi @farazBhatti
thanks for your response
I running it on CPU configuration
got this error:
ERROR: Could not find a version that satisfies the requirement tensorflow==1.13.1 (from versions: 2.8.0rc0, 2.8.0rc1, 2.8.0, 2.8.1, 2.8.2, 2.8.3, 2.8.4, 2.9.0rc0, 2.9.0rc1, 2.9.0rc2, 2.9.0, 2.9.1, 2.9.2, 2.9.3, 2.10.0rc0, 2.10.0rc1, 2.10.0rc2, 2.10.0rc3, 2.10.0, 2.10.1, 2.11.0rc0, 2.11.0rc1, 2.11.0rc2, 2.11.0, 2.11.1, 2.12.0rc0, 2.12.0rc1, 2.12.0, 2.12.1, 2.13.0rc0, 2.13.0rc1, 2.13.0rc2, 2.13.0, 2.13.1, 2.14.0rc0, 2.14.0rc1, 2.14.0, 2.14.1, 2.15.0rc0, 2.15.0rc1, 2.15.0, 2.15.0.post1, 2.15.1, 2.16.0rc0, 2.16.1)
ERROR: No matching distribution found for tensorflow==1.13.1

**Comment by Rut-B** [comment]
hi @farazBhatti
thanks for your response
did it, but got different error:

Failed to build opendr
ERROR: Could not build wheels for opendr, which is required to install pyproject.toml-based projects
---------------------------------------------------------------------------

you can see the code here:

https://colab.research.google.com/drive/1gD5XPShENF9-p7YUY9N1alB2Y0g_Ux6o?usp=sharing

**Comment by farazBhatti** [comment]
i ran notebook without any errors

**Comment by Rut-B** [comment]
thanks @farazBhatti  of your answer and help!
did you run my notebook?
can you share your notebook that succeeded to run?
thanks alot
