### ISSUE TITLE
Missing file: customBodyPoints.txt

### ISSUE THREAD

**Issue by sam189239** [farazBhatti/Human-Body-Measurements-using-Computer-Vision#5]
I tried to run the code and I'm stuck with this issue.
The file is not present in the repo.
FileNotFoundError: [Errno 2] No such file or directory: 'data/customBodyPoints.txt'

**Comment by farazBhatti** [comment]
@sam189239  please find it [here](https://github.com/farazBhatti/Human-Body-Measurements-using-Computer-Vision/issues/1#issuecomment-768931614)

**Comment by sam189239** [comment]
Thank you sir, it worked.. But is this specific to the sample image? Should we generate a BodyPoints file for new images? I was not able to get satisfying results on other images.. If yes, how to generate the file. Your response would be of great help.

**Comment by farazBhatti** [comment]
this file is general. No need to generate new  bodyPoints file.  As for results I have tested it on many images, im not really sure why you getting bad results
