### ISSUE TITLE
Implement 

### ISSUE THREAD

**Issue by weeraaaaaa1234** [farazBhatti/Human-Body-Measurements-using-Computer-Vision#6]
how does it work? can you explain, please As soon as possible

**Comment by farazBhatti** [comment]
can you please specify your problem? Are you having some issues in running this repo?

**Comment by weeraaaaaa1234** [comment]
Yes, I have a question about how the path and height of the image are given
on PowerShell. how to solve this. can you please explain me?

**Comment by farazBhatti** [comment]
if your image is e.g "input_image.png" is saved in root dir and the height of person in image is lets say 170 cm, then you will type the following command in shell:

python3 inference.py -i input_image.png -ht 170
