### ISSUE TITLE
customBodyPoints.txt missing

### ISSUE THREAD

**Issue by iggyfull** [farazBhatti/Human-Body-Measurements-using-Computer-Vision#7]
Hi Faraz, I am trying to run your code and it throws me this error:

```
Traceback (most recent call last):
  File "inference.py", line 217, in <module>
    main(bg_removed,args.height,None)
  File "C:\temp\body\demo.py", line 148, in main
    extract_measurements.extract_measurements(height,verts[0])
  File "C:\temp\body\extract_measurements.py", line 111, in extract_measurements
    cp = convert_cp()
  File "C:\temp\body\extract_measurements.py", line 48, in convert_cp
    f = open(os.path.join(DATA_DIR, 'customBodyPoints.txt'), "r")
FileNotFoundError: [Errno 2] No such file or directory: 'data\\customBodyPoints.txt'
```

Some _**customBodyPoints.txt**_ file is missing in the repo. I've tried using _body_control_points.txt_ from your other repo "_3D-Human-Body-Shape_" but that doesn't seem to work.

However, if I avoid entering extract_measurements.py from demo.py and uncomment the model writing structure, it seems to work perfectly.

In any case, great job!

**Comment by farazBhatti** [comment]
I've updated readme file. you can also download it from [here](https://github.com/farazBhatti/Human-Body-Measurements-using-Computer-Vision/files/5886235/customBodyPoints.txt).
