### ISSUE TITLE
Models

### ISSUE THREAD

**Issue by LESNAROP** [farazBhatti/Human-Body-Measurements-using-Computer-Vision#8]
Cannot locate the models folder

**Comment by LESNAROP** [comment]
![16225795919764780198207675288776](https://user-images.githubusercontent.com/85095719/120386797-b8c55800-c346-11eb-9f4b-ed9dd1e01496.jpg)

**Comment by LESNAROP** [comment]
![16225844652161868083718733334603](https://user-images.githubusercontent.com/85095719/120395102-10b58c00-c352-11eb-98cb-ecb31e3eb2ba.jpg)
Kindly help sir

**Comment by amol-17** [comment]
I am getting the same issue as well. May i know any solution?
![image](https://user-images.githubusercontent.com/48273293/120424443-fd261780-c389-11eb-9da6-c27ffa67ce4e.png)

**Comment by farazBhatti** [comment]
what TensorFlow versions are you using? this code is tested on tensorflow==1.13.1. to install it you can do the following
1- pip uninstall tensorflow -y
2- pip install tensorflow==1.13.1

**Comment by Vedant13-ux** [comment]
![WhatsApp Image 2021-06-02 at 2 13 29 PM](https://user-images.githubusercontent.com/56965523/120449309-efce5480-c3ac-11eb-9faa-27527c59e8f5.jpeg)
I tried to install tensorflow==1.13.1 and also installed the python 3.6 version but it s showing me his error, I also tried to install this version of tensorflow using python 3.9 but the error was same

**Comment by farazBhatti** [comment]
try install tensorflow independently.
sudo pip3 install tensorflow==1.13.1
