### ISSUE TITLE
Running on Local Machine

### ISSUE THREAD

**Issue by rishik-00** [farazBhatti/Human-Body-Measurements-using-Computer-Vision#9]
I am having trouble while running this on local machine.
Steps I have done till now:
1. cloned the repo
2.  downloaded the pre trained models and place it in models folder
3. place custom text file in a new data 
4. running pip install -r requirements.txt to install modules

Step 4 is giving me errors, i dont know the reason for it, It is giving me error in both globally or while using venv
![Screenshot (7)](https://user-images.githubusercontent.com/43490153/120446867-97e11f00-c3a7-11eb-928e-fee1f6a3ed32.png)

**Comment by rishik-00** [comment]
Please help me

**Comment by farazBhatti** [comment]
try using sudo command. i am not sure this error is due to repo or not

**Comment by rishik-00** [comment]
I am on windows

**Comment by rishik-00** [comment]
Are these steps i have done correct?, Do i need to do anything more?, Is there any other way to download all the required modules??

**Comment by farazBhatti** [comment]
download them indepedently without using requirement file.
